apiVersion: v1
kind: Service
metadata:
  name: pl-app
  labels:
    app: pl-app
spec:
  type: LoadBalancer
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 8080
  selector:
    app: pl-app
status:
  loadBalancer: { }