resources:
- deployments/pl-app-deployment.yaml
- services/service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jpumpkin93/pl-app
  newName: jpumpkin93/pl-app
  newTag: "2"
